### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by an9wer** [manateelazycat/manateelazycat.github.io#1]
Hi, I am a reader of your blog, and before used some RSS reader to subscribe to your blog in JianShu by using [RSSHub](https://github.com/DIYgod/RSSHub).

As you have migrated to GitHub to publish your posts, could you also provide RSS feed, so I can notice the update of your blog?

**Comment by manateelazycat** [comment]
最近加班, 我周末添加RSS

**Comment by an9wer** [comment]
Thank you so much :)

**Comment by manateelazycat** [comment]
http://localhost:4000/feed.xml 已经添加了 Atom Feeds
