### ISSUE TITLE
分页功能讨论

### ISSUE THREAD

**Issue by 98wb** [manateelazycat/manateelazycat.github.io#10]
感谢勇哥的 Jekyll 博客，依您的样式为模版，套了[一份](https://github.com/98wb/98wb.github.io)：

[五笔小筑](https://98wb.github.io/)

Jekyll 的分页不太友好，这可能是您一直没有添加分页的原因吧，现在，我初步实现了分页，在配置文件中，它是这样的：

1: 安装分页的官方插件
> gem install jekyll-paginate

2: [config.yml](https://github.com/98wb/98wb.github.io/blob/master/_config.yml) 写入声明
``````
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "page:num"
``````

3: [index.html](https://github.com/98wb/98wb.github.io/blob/master/index.html)中删掉旧的流式布局定义

``````
{% for post in site.posts %}
...
...
...
{% endfor %}
``````

4: [layouts/home.html](https://github.com/98wb/98wb.github.io/blob/master/_layouts/home.html)中添加新的分页定义：

https://github.com/98wb/98wb.github.io/blob/5662f0ea057cb1aeb5c68a3ce3a8c56ac4a84da9/_layouts/home.html#L17-L78

5: 清空「_site」，重新部署 jekyll server

如此以来，分页就生效了。「index.html」中的旧定义删掉，让「layouts/home.html」中的新定义来补充，就简单实现了可用的分页。

具体效果，[见此](https://98wb.github.io/page4/)。

功能虽然实现了，但是缺点您也应当想到了，文章分页时，所有页面都将全部显示出来。如果**总页码数量**过多，必然造成版面突兀和撕裂。

从纯粹的 HTML 语言上，似乎有实现分页控制的可能性，比如：

https://www.cnblogs.com/llcdbk/p/5542498.html

该篇博客，以「10页显示上限」为例，做了代码展示。他的思路是很好的，如果**总页码数量**过多，可以转跳或变换显示页码。

如果纯粹的标签语言在实现上有问题，Jekyll 还有 JS 支持，能引入自己目录下的 JS 文件。比如，我就在网上扒着资料，给博客添加了 MathJax 支持，能显示 LaTex 数学公式：

https://github.com/98wb/98wb.github.io/tree/master/assets/js

关于可能有用的 Jekyll 内部变量，这里有一些：

https://jekyllcn.com/docs/pagination/

实际上具体分页的实现，我就是参照这个 Jekyll 官方中文文档实现的，但是它的代码与我们的博客样式不符，我已经做了适应于我们样式的修改，使它可用了。

这是目前已达成的效果和它的缺陷，以及弥补缺陷可能有用的思路与资料。

我对前端类的语言几乎一窍不通，很艰难地做了上述功课。在勇哥这里提 issue ，是希望勇哥可以更进一步，将分页功能在我们博客样式上的实现做得更丰满一些，如果转跳的实现有困难，即使仅能实现类似「10页显示上限」那位作者所展示的样子也够了。

文章数量过多时，流式布局有其天然的短板，如果勇哥太忙，也希望能采纳一下既有的，不太完美的实现，比如值设为「30~40」，以减少分页后得到的最终总页数。

https://github.com/98wb/98wb.github.io/blob/5662f0ea057cb1aeb5c68a3ce3a8c56ac4a84da9/_config.yml#L21

祝安，以上。

**Comment by manateelazycat** [comment]
哈哈哈，我就是不想要分页，懒得折腾，一个博客CSS适配完就全部完了。

不过谢谢你的建议，我主要太懒了，不想折腾这些细节哈。 ;)
