### ISSUE TITLE
几处错别字

### ISSUE THREAD

**Issue by lookat23** [manateelazycat/manateelazycat.github.io#14]
这些错别字都是无关重要，但我心情低落或者工作上遇到难题总喜欢看看勇哥的博客，总能给我力量。也不知能回报什么，  看到有些错字记了下来。
#### 读《当下的力量》
接纳世间的好**于**坏  

#### 读书分享与创业杂谈
为什么不**参见**今年的武汉马拉松
有时候你**的**说服自己  
流程**就想**做产品设计一样  
你要**清新**自己目前还深处暗处  
同僚之间**大大**桌面足球  
企业文化就像**上号**的苏格兰威士忌一样

**Comment by manateelazycat** [comment]
哈哈哈，谢谢你，错别字已经修改。

人生很长，慢慢来，送你一句话：

This too will past...

控制不住自己的时候，多想想这句话。

**Comment by lookat23** [comment]
谢谢勇哥鼓励
