### ISSUE TITLE
project 里面有错字

### ISSUE THREAD

**Issue by CyrusYip** [manateelazycat/manateelazycat.github.io#21]
aweshell
基于eshell开发的终端管理器插件，包括Shell命令补全、ZSH风格提示符、底部固定终端、Fish风格最佳匹配建议、语法高亮Cat命令、命令状态提示等高级功能。现在是我最**长用**的终端插件。

这里应该是**常用**吧。

本来想发pull request的，但是不知道在哪个文件改。

**Comment by manateelazycat** [comment]
已经修复，谢谢反馈
