### ISSUE TITLE
《英语魔法师之语法俱乐部》过时了

### ISSUE THREAD

**Issue by CyrusYip** [manateelazycat/manateelazycat.github.io#25]
看你在[这篇博客](https://manateelazycat.github.io/reading/2022/11/15/reading-english-magicia.html)提到《语法俱乐部》，这本书的原版是《英文魔法師之文法俱樂部》，1998 年出版。现在最新版是2019年出版的《 旋元佑文法 》，内容多了很多，推荐读这个。

顺便问一下，能不能给博客加个评论功能呢，这样比较方便大家交流。最近这个项目挺流行的：https://github.com/giscus/giscus 。

**Comment by manateelazycat** [comment]
感谢告知。

不太想折腾评论，不太在意别人的想法。
