### ISSUE TITLE
关于 Markdown CSS 的定义

### ISSUE THREAD

**Issue by fenjianxiaozhu** [manateelazycat/manateelazycat.github.io#3]
拜读大佬的 [技术贴](https://manateelazycat.github.io/tech/2019/04/24/jekyll.html) 时，有个疑问：

关于「让所有图片都自动缩放成页面的宽度」这一节：

![1](https://raw.githubusercontent.com/richblend2019/tingtao.github.io/master/1.png)

![2](https://raw.githubusercontent.com/richblend2019/tingtao.github.io/master/2.png)

**Comment by manateelazycat** [comment]
第一个，我发现用 p>img 的选择器比 {.center-image} 的方式更好

第二个，在 https://github.com/manateelazycat/manateelazycat.github.io/blob/master/styles/post.css

**Comment by fenjianxiaozhu** [comment]
这么晚了老大还没睡啊，主页是否可以考虑分一下页呢，比如15~20篇分一页，文章标题像瀑布一样，不方便阅读。
